# Generated by Django 4.2.3 on 2023-08-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='media/')),
                ('fileURL', models.CharField(max_length=50)),
                ('tag', models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('pdf', 'Pdf')], max_length=10)),
                ('topics', models.CharField(choices=[('babyDev', 'BabyDev'), ('babyHealth', 'BabyHealth'), ('parentHealth', 'ParentHealth')], max_length=15)),
                ('language', models.CharField(choices=[('english', 'English'), ('xhosa', 'Xhosa'), ('shona', 'Shona')], max_length=8)),
            ],
            options={
                'db_table': 'Content',
            },
        ),
    ]
