# Generated by Django 4.2.3 on 2023-08-03 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='fileURL',
        ),
    ]
