# Generated by Django 4.2.3 on 2023-08-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_content_fileurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='topics',
            field=models.CharField(choices=[('babyDev', 'Baby Development'), ('babyHealth', 'Baby Health'), ('parentHealth', 'Parent Health')], max_length=15),
        ),
    ]
