# Generated by Django 4.2.3 on 2023-08-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_content_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('isiXhosa', 'IsiXhosa'), ('chiShona', 'ChiShona')], max_length=8),
        ),
    ]
