# Generated by Django 4.2.3 on 2023-08-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_content_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='visible',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='Public', max_length=10),
            preserve_default=False,
        ),
    ]
