# Generated by Django 4.2.3 on 2023-08-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_content_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='content',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('IsiXhosa', 'IsiXhosa'), ('ChiShona', 'ChiShona'), ('Afrikaans', 'Afrikaans')], max_length=15),
        ),
    ]
