# Generated by Django 4.2.3 on 2023-08-04 20:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0011_alter_content_file_alter_content_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='assignedUsers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
