# Generated by Django 4.2.3 on 2023-08-04 21:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_content_assignedusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='assignedUsers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
